### ISSUE TITLE
Issue on parsing

### ISSUE THREAD

**Issue by ac06012014** [yhejazi/mtg-web-scraper#13]
Hi Yasmine,
First of all, thanks a lot for this tool. I've got an issue (first time I launched it). Do you have any idea please ?

Scraping page 106/214
Traceback (most recent call last):
  File "/Users/ac06012014/Downloads/mtg/mtg-web-scraper/mtg_card_scraper.py", line 50, in <module>
    manaCostList.append(convertSymbol(cost['alt']))
  File "/Users/ac06012014/Downloads/mtg/mtg-web-scraper/helper.py", line 27, in convertSymbol
    raise Exception('Could not parse symbol:{}'.format(imgAlt))
Exception: Could not parse symbol:Half a White

**Comment by yhejazi** [comment]
Thanks for the call out!
